yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.error_pages.views.page_not_found'

handler500 = 'core.error_pages.views.server_error'

handler403 = 'core.error_pages.views.permission_denied'

# В режиме разработки загружать статические картинки
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/templates/about/author.html
{% extends "base.html" %}


{% block title %}
  Об авторе проекта
{% endblock %}


{% block content %}
<div class="information-text information-text_margin_bottom">
  <h1 class="information-text__title">
    Привет, меня зовут Рустам.
  </h1>
</div>

<p class="fs-5" style="color: #121212">
  В свободное время поработаю с 
  <span style="color: #ffc107" class="fw-bolder">
    bootstrap 5
  </span>
  |
  <span style="color: #ffc107" class="fw-bolder">
    bootstrap UI
  </span>
  |
  <span style="color: #ffc107" class="fw-bolder">
    jQuery
  </span>
</p>

<a href="{% url 'about:tech' %}"
    class="
      btn 
      btn-outline-primary
      w-25
      mt-5 
      btn-lg"
  >
  Технологии
</a>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}


{% block title %}
  Технологии
{% endblock %}


{% block content %}
<div class="information-text information-text_margin_bottom">
  <h1 class="information-text__title">
    Вот что я умею
  </h1>
</div>

<aside class="col-12 col-md-3 me-5">
  <ul class="list-group list-group-flush">
    <li class="fs-5 fw-bolder"
      style="color: #ffc107"
    >
      Python
    </li>
    <li class="fs-5 fw-bolder"
      style="color: #ffc107"
    >
      Django framework
    </li>
    <li class="fs-5 fw-bolder"
      style="color: #ffc107"
    >
      Git
    </li>
    <li class="fs-5 fw-bolder"
      style="color: #ffc107"
    >
      SQL / SQLite
    </li>
  </ul>
</aside>

<article class="col-12 col-md-8">
  <p class="fs-5" 
    style="color: #121212"
  >
    Применяю полученные знания на практике.
  </p>
</article>

<a href="{% url 'about:author' %}" 
  class="
    btn 
    btn-outline-primary
    w-25 
    mx-auto 
    mt-5 
    btn-lg"
>
  Автор
</a>
{% endblock %} 