yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    )
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

follow_post = (
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'follow/<str:username>/',
        views.follow_author,
        name='follow_author'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    )
)

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_posts'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/delete/',
        views.post_delete,
        name='post_delete'
    ),
    path(
        'posts/<int:comment_id>/comment/delete/',
        views.comment_delete,
        name='comment_delete'
    ),
    *follow_post
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.error_pages.views.page_not_found'

handler500 = 'core.error_pages.views.server_error'

handler403 = 'core.error_pages.views.permission_denied'

# В режиме разработки загружать статические картинки
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.general_models.models import Date

User = get_user_model()


class Post(Date):
    text = models.TextField(
        verbose_name='Описание',
        help_text='Введите описание поста'
    )
    post_edit = models.BooleanField(
        default=False,
        verbose_name='Изменен ли пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Выберите автора'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )

    class Meta:
        ordering = ['-edited']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return f'Описание: {self.text[:15]}...'


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Заголовок'
    )
    slug = models.SlugField(
        max_length=40,
        unique=True,
        default='category-',
        verbose_name='Путь'
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Comment(Date):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Выберите пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Выберите автора'
    )
    text = models.TextField(
        verbose_name='Комментарий',
        help_text='Введите комментарий'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return f'Описание: {self.text[:15]}...'


class Follow(Date):
    # Текущий пользователь
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    # Автор поста
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Подписки'
        verbose_name_plural = 'Подписки'

    def __str__(self) -> str:
        return self.user.username

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment

        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import Post, Group, User, Comment, Follow
from .forms import PostForm, CommentForm


AMOUNT_POSTS_ON_ONE_PAGE = 10


def get_pagination(request, posts, amount):
    paginator = Paginator(posts, amount)

    page_number = request.GET.get('page')

    return paginator.get_page(page_number)


def index(request):
    author = request.user

    posts = Post.objects.select_related('group').all()

    page_obj = get_pagination(request, posts, AMOUNT_POSTS_ON_ONE_PAGE)

    context = {
        'author': author,
        'page_obj': page_obj
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)

    posts = group.posts.all()

    page_obj = get_pagination(request, posts, AMOUNT_POSTS_ON_ONE_PAGE)

    context = {
        'group': group,
        'page_obj': page_obj
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):

    author = get_object_or_404(User, username=username)

    posts = author.posts.all()

    page_obj = get_pagination(request, posts, AMOUNT_POSTS_ON_ONE_PAGE)

    following = User.objects.filter(following__author=author).exists()

    is_author = author == request.user

    context = {
        'page_obj': page_obj,
        'post_count': page_obj.paginator.count,
        'author': author,
        'following': following,
        'is_author': is_author
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):

    post = get_object_or_404(Post, pk=post_id)

    comments = post.comments.all()

    post_count = post.author.posts.count()

    author = request.user

    form = CommentForm(request.POST or None)

    context = {
        'post': post,
        'post_count': post_count,
        'author': author,
        'form': form,
        'comments': comments
    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):

    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )

    if not form.is_valid():

        context = {
            'form': form,
            'is_edit': False
        }

        return render(request, 'posts/create_post.html', context)

    author = request.user

    fields = form.save(commit=False)

    fields.author = author

    form.save()

    return redirect('posts:profile', author.username)


@login_required
def post_edit(request, post_id):
    author = request.user

    post = get_object_or_404(Post, pk=post_id)

    if not post.author == author:
        return redirect('posts:post_detail', post.id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )

    if not form.is_valid():

        context = {
            'post': post,
            'form': form,
            'is_edit': True
        }

        return render(request, 'posts/create_post.html', context)

    fields = form.save(commit=False)

    fields.post_edit = True

    form.save()

    return redirect('posts:post_detail', post.id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    form = CommentForm(request.POST or None)

    if form.is_valid():
        fields = form.save(commit=False)

        fields.author = request.user
        fields.post = post

        form.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_delete(request, post_id):
    author = request.user

    post = get_object_or_404(Post, pk=post_id)

    if post.author == author:
        post.delete()

    return redirect('posts:index')


@login_required
def comment_delete(request, comment_id):
    author = request.user

    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == author:
        comment.delete()

    return redirect('posts:post_detail', comment.post.id)


@login_required
def follow_index(request):
    """ Избранные посты авторов. """

    # В постах, у автора, узнаем на что он подписан
    posts = Post.objects.filter(author__following__user=request.user)

    page_obj = get_pagination(request, posts, AMOUNT_POSTS_ON_ONE_PAGE)

    authors = User.objects.filter(following__user=request.user)

    context = {
        'page_obj': page_obj,
        'authors': authors
    }

    return render(request, 'posts/follow.html', context)


@login_required
def follow_author(request, username):
    """ Перейти на посты автора. """
    posts = Post.objects.filter(author__following__author__username=username)

    page_obj = get_pagination(request, posts, AMOUNT_POSTS_ON_ONE_PAGE)

    authors = User.objects.filter(following__user=request.user)

    context = {
        'page_obj': page_obj,
        'authors': authors,
        'username': username
    }

    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """ Подписаться. """

    # Автор поста
    author = get_object_or_404(User, username=username)

    # Текущий пользователь
    user = request.user

    # Автор, не может подписаться сам на себя
    if not author == user:
        obj, created = Follow.objects.get_or_create(user=user, author=author)

    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """ Отписаться. """

    # Автор поста
    follow = Follow.objects.filter(
        author__username=username,
        user__username=request.user
    )

    follow.delete()

    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}


{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %} 
{% endblock %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %} Редактировать пост {% else %} Новый пост {% endif %}
      </div>

      <div class="card-body">
        {% include 'includes/form/form_error.html' %}

        <form
          method="post"
          action="
          {% if is_edit %}
            {% url 'posts:post_edit' post.id %}
          {% else %}
            {% url 'posts:post_create' %}
          {% endif %}"
          enctype="multipart/form-data"
        >
          {% csrf_token %} {% for field in form %}
          <div class="form-group row my-3 p-3">
            {% include 'includes/form/form_field.html' %}
          </div>
          {% endfor %}

          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
            </button>
          </div>
        </form>
      </div>
      <!-- card-body -->
    </div>
    <!-- card -->
  </div>
  <!-- col -->
</div>
<!-- row  -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block title %}
  Это главная страница проекта Yatube
{% endblock %}


{% block content %}
<div class="information-text information-text_margin_bottom">
  <h1 class="information-text__title">
    Все посты
  {% if username %}
    автора {{ username }}
  {% endif %}
  </h1>
</div>

{% include 'includes/switcher.html' %}

{% if user.is_authenticated %}
  {% with request.resolver_match.view_name as current_url %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if current_url == 'posts:follow_index' %}active{% endif %}"
          href="{% url 'posts:follow_index' %}"
        >
          Все посты
        </a>
      </li>

      {% for author in authors %}
        <li class="nav-item">
          <a 
            class="nav-link {% if current_url == 'posts:follow_author' %}active{% endif %}"
            href="{% url 'posts:follow_author' author %}"
          >
            {{ author }}
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
  {% endwith %} 
{% endif %}

<div class="posts">
  <ul class="posts__list">
    {% for post in page_obj %}
      <li class="posts__item">
        <article class="card-post">

          {% include 'includes/posts.html' %}

          <div class="row mt-5">
            {% include 'includes/buttons/detail_link.html' %}

            {% if post.group %}
              {% include 'includes/buttons/group_link.html' %}
            {% endif %}
          </div>
        </article>
      </li>
    {% empty %}
      <p>Пока нет записей.</p>
    {% endfor %}
  </ul>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}


{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %} 


{% block content %}
<div class="information-text information-text_margin_bottom">
  <h1 class="information-text__title">
    {{ group.title }}
  </h1>

  <p>
    {{ group.description }}
  </p>
</div>

<div class="posts">
  <ul class="posts__list">
    {% for post in page_obj %}
      <li class="posts__item">
        <article class="card-post">
          {% include 'includes/posts.html' %}

          {% include 'includes/buttons/detail_link.html' %}
        </article>
      </li>
    {% empty %}
      <p>В этой категории нет записей.</p>
    {% endfor %}
  </ul>
</div>

{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}


{% block title %}
  Это главная страница проекта Yatube
{% endblock %}


{% block content %}
{% cache 20 index page_obj.number %}
<div class="information-text information-text_margin_bottom">
  <h1 class="information-text__title">
    Последние обновления на сайте
  </h1>
</div>

{% include 'includes/switcher.html' %}

<div class="posts">
  <ul class="posts__list">
    {% for post in page_obj %}
      <li class="posts__item">
        <article class="card-post">

          {% include 'includes/posts.html' %}

          <div class="row mt-5">
            {% include 'includes/buttons/detail_link.html' %}

            {% if post.group %}
              {% include 'includes/buttons/group_link.html' %}
            {% endif %}

            {% if post.author == author %}
              {% include 'includes/buttons/delete_link.html' %}
            {% endif %}
          </div>
        </article>
      </li>
    {% empty %}
      <p>Пока нет записей.</p>
    {% endfor %}
  </ul>
</div>

{% include 'includes/paginator.html' %}
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block title %}
  Пост {{ post.text|truncatechars:30}}
{% endblock %} 


{% block content %}
<div class="row">
  <aside class="col-12 col-md-4 me-5">
    <ul class="list-group list-group-flush">
      <li
        class="list-group-item d-flex justify-content-between align-items-center"
        style="color: #f5556e"
      >
        Дата публикации &#8213;
        <span style="color: #dedede" class="fw-bolder">
          {{ post.created|date:'d E Y' }}
        </span>
      </li>

      <li
        class="list-group-item d-flex justify-content-between align-items-center"
        style="color: #f5556e"
      >
        Автор &#8213;
        <span style="color: #dedede" class="fw-bolder">
          {% if post.author.get_full_name %}
            {{ post.author.get_full_name }}
          {% else %}
            {{ post.author }}
          {% endif %}
        </span>
      </li>

      <li
        class="list-group-item d-flex justify-content-between align-items-center"
        style="color: #f5556e"
      >
        Всего постов автора &#8213;
        <span style="color: #dedede" class="fw-bolder"> {{ post_count }} </span>
      </li>

      <li
        class="list-group-item d-flex justify-content-between align-items-center"
        style="color: #f5556e"
      >
        {% if post.group %} Группа &#8213;
          <span style="color: #dedede" class="fw-bolder"> {{ post.group }} </span>
        {% endif %}
      </li>

      <li class="list-group-item row">
        {% if post.group %}
        <a
          href="{% url 'posts:group_posts' post.group.slug %}"
          class="btn btn-outline-primary mb-2"
        >
          все записи группы
        </a>
        {% endif %}
        <a
          href="{% url 'posts:profile' post.author.username %}"
          class="btn btn-outline-primary mb-2"
        >
          все посты пользователя
        </a>
        {% if post.author == author %}
        <a
          href="{% url 'posts:post_edit' post.id %}"
          class="btn btn-outline-primary"
        >
          редактировать пост
        </a>
        {% endif %}
      </li>
    </ul>
  </aside>
  
  <article class="col-12 col-md-7">
    <p style="color: #6e6e6e" class="fs-5">
      {{ post.text }}
    </p>
    {% thumbnail post.image "740x418" crop="center" upscale=True as image %}
      <img class="card-img my-2" src="{{ image.url }}">
    {% endthumbnail %}
  </article>

  {% if user.is_authenticated %}
    <div class="card my-4">
      <h5 class="card-header">
        Добавить комментарий:
      </h5>

      <div class="card-body">
        {% include 'includes/form/form_error.html' %}

        <form method="post" action="{% url 'posts:add_comment' post.id %}">
          {% csrf_token %} {% for field in form %}
          <div class="form-group mb-2">
            {% include 'includes/form/form_field.html' %}
          </div>
        {% endfor %}

          <button type="submit" class="btn btn-primary">
            Отправить
          </button>
        </form>
      </div>

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>

            <p>
              {{ comment.text }}
            </p>

            {% if comment.author == author %}
              <a href="{% url 'posts:comment_delete' comment.pk %}" class="btn btn-outline-danger w-25">
                Удалить
              </a>
            {% endif %}
          </div>
        </div>
      {% endfor %}
    </div>
  {% endif %}
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}


{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}


{% block content %}
<div class="information-text information-text_margin_bottom">
  <h1 class="information-text__title">
    Все посты пользователя {{ author }}
  </h1>

  <p class="information-text__description">
    Всего постов: {{ post_count }}
  </p>
</div>

{% if user.is_authenticated and not is_author %}
{% if following %}
  <a
    class="btn btn-lg btn-light"
    href="{% url 'posts:profile_unfollow' author.username %}" role="button"
  >
    Отписаться
  </a>
{% else %}
  <a
    class="btn btn-lg btn-primary"
    href="{% url 'posts:profile_follow' author.username %}" role="button"
  >
    Подписаться
  </a>
{% endif %}
{% endif %}

<div class="posts">
  <ul class="posts__list">
    {% for post in page_obj %}
      <li class="posts__item">
        <article class="card-post">

          {% include 'includes/posts.html' %}

          <div class="row mt-5">
            {% include 'includes/buttons/detail_link.html' %}

            {% if post.group %}
              {% include 'includes/buttons/group_link.html' %}
            {% endif %}
          </div>
        </article>
      </li>
    {% empty %}
      <p>В этой категории нет записей.</p>
    {% endfor %}
  </ul>
</div>

{% include 'includes/paginator.html' %}
{% endblock %}