yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author'
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech'
    )
]

yatube/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    PasswordChangeView,
    PasswordChangeDoneView,
    LogoutView
)

from .views import (
    PasswordReset,
    PasswordResetComplete,
    SignUp
)


app_name = 'users'

"""
Пути сброса пароля.
Доступно только авторизированным пользователям.
"""
password_reset = (
    path(
        'password_reset/',
        PasswordReset.as_view(),
        name='reset_form'
    ),
    path(
        'reset/done/',
        PasswordChangeView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetComplete.as_view(),
        name='reset_done'
    ),
)

"""
Пути смены пароля.
Доступно только авторизированным пользователям.
"""
password_change = (
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='done'
    ),
)

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    *password_change,
    *password_reset
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.error_pages.views.page_not_found'

handler500 = 'core.error_pages.views.server_error'

handler403 = 'core.error_pages.views.permission_denied'

# В режиме разработки загружать статические картинки
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/models.py
# Create your models here.

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationFormUser(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetCompleteView,
)

from .forms import CreationFormUser


class SignUp(CreateView):
    form_class = CreationFormUser

    template_name = 'users/signup.html'

    success_url = reverse_lazy('posts:index')


class PasswordReset(PasswordResetView):
    """ Сменить пароль может только зарегистрированный пользователь. """
    template_name = 'users/password_reset_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PasswordResetComplete(PasswordResetCompleteView):
    """
    Подтверждения отправки письма на почту,
    может видеть только зарегистрированный пользователь.
    """
    template_name = 'users/password_reset_done.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

yatube/templates/users/logged_out.html
{% extends 'base.html' %}


{% block title %}
  Вы вышли из системы
{% endblock %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <article class='mb-3'
      style="
        border: 1px solid #F5F5F5; 
        border-radius: 5px; padding: 30px
      "
    >
      <h1 style="color: #121212" class="fs-4 mb-4">
        Выход
      </h1>

      <p style="color: #6E6E6E">
        Вы вышли из своей учётной записи. Ждём вас снова!
      </p>
    </article>
  </div> 
  <!-- col -->
</div> 
<!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}


{% block title %}
  Войти
{% endblock %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <article class='mb-3'
      style="
        border: 1px solid #F5F5F5; 
        border-radius: 5px; padding: 40px
      "
    >

      <h1 style="color: #121212" class="fs-4">
        Войти на сайт
      </h1>
      
      <div>
        {% include 'includes/form/form_error.html' %}

        <form method="post" action="{% url 'users:login' %}">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              {% include 'includes/form/form_field.html' %}
            </div>
          {% endfor %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>

            <a href="{% url 'users:change' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
        </form>
      </div>
    </article>
  </div> 
  <!-- col -->
</div> 
<!-- row -->
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends "base.html" %}


{% block title %}
  Пароль изменён
{% endblock %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <article class='mb-3'
      style="
        border: 1px solid #F5F5F5; 
        border-radius: 5px; padding: 30px
      "
    >
      <h1 style="color: #121212" class="fs-4 mb-4">
        Пароль изменён
      </h1>

      <p style="color: #6E6E6E">
        Пароль успешно изменён
      </p>
    </article> 
  </div> 
  <!-- col -->
</div> 
<!-- row -->
{% endblock %} 

yatube/templates/users/password_change_form.html
{% extends "base.html" %}


{% block title %}
  Изменение пароля
{% endblock %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <article class='mb-3'
      style="
        border: 1px solid #F5F5F5; 
        border-radius: 5px; padding: 40px
      "
    >

      <h1 style="color: #121212" class="fs-4">
        Изменить пароль
      </h1>

      <div>
        {% include 'includes/form/form_error.html' %}

        <form method="post" action="">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              {% include 'includes/form/form_field.html' %}
            </div>
          {% endfor %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Изменить пароль
            </button>
          </div>
        </form>
      </div>
    </article>
  </div> 
  <!-- col -->
</div> 
<!-- row -->
{% endblock %} 

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}


{% block title %}
  Сброс пароля прошёл успешно
{% endblock %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <article class='mb-3'
      style="
        border: 1px solid #F5F5F5; 
        border-radius: 5px; padding: 30px
      "
    >
      <h1 style="color: #121212" class="fs-4 mb-4">
        Восстановление пароля завершено
      </h1>
      
      <div>
        <p style="color: #6E6E6E">
          Ваш пароль был сохранен. Используйте его для входа
        </p>
        <a href="{% url 'users:login' %}">
          войти
        </a>
      </div>
    </article>
  </div> 
  <!-- col -->
</div> 
<!-- row -->
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}


{% block title %}
  Сброс пароля прошёл успешно
{% endblock %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <article class='mb-3'
      style="
        border: 1px solid #F5F5F5; 
        border-radius: 5px; padding: 30px
      "
    >
      <h1 style="color: #121212" class="fs-4 mb-4">
        Отправлено письмо
      </h1>

      <p style="color: #6E6E6E">
        Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля
      </p>
    </article>
  </div> 
  <!-- col -->
</div> 
<!-- row -->
{% endblock %} 

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}


{% block title %}
  Сброс пароля
{% endblock %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <article class='mb-3'
      style="
        border: 1px solid #F5F5F5; 
        border-radius: 5px; padding: 40px
      "
    >

      <h1 style="color: #121212" class="fs-5">
        Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
      </h1>

      <div class="card-body">

        {% include 'includes/form/form_error.html' %}

        <form method="post" action="">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              {% include 'includes/form/form_field.html' %}
            </div>
          {% endfor %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Сбросить пароль
            </button>
          </div>
        </form>
      </div>
    </article> 
    <!-- card -->
  </div> 
  <!-- col -->
</div> 
<!-- row -->
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}


{% block title %}
  Зарегистрироваться
{% endblock %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <article class='mb-3'
      style="
        border: 1px solid #F5F5F5; 
        border-radius: 5px; padding: 40px
      "
    >

      <h1 style="color: #121212" class="fs-4">
        Зарегистрироваться
      </h1>

      <div>
        {% include 'includes/form/form_error.html' %}

        <form method="post" action="{% url 'users:signup' %}">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3 p-3">
              {% include 'includes/form/form_field.html' %}
            </div>
          {% endfor %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>
      </div>
    </article> 
    <!-- card -->
  </div> 
  <!-- col -->
</div> 
<!-- row -->
{% endblock %} 